/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedComposeRouteImport } from './routes/_protected/compose'
import { Route as ProtectedProspectsIndexRouteImport } from './routes/_protected/prospects/index'
import { Route as ApiNangoWebhookRouteImport } from './routes/api/nango/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedProspectsImportRouteImport } from './routes/_protected/prospects/import'
import { Route as ProtectedProspectsIdRouteImport } from './routes/_protected/prospects/$id'
import { Route as ProtectedSettingsMailboxesIndexRouteImport } from './routes/_protected/settings/mailboxes/index'
import { Route as ProtectedSettingsCrmIndexRouteImport } from './routes/_protected/settings/crm/index'
import { Route as ProtectedSettingsMailboxesNewRouteImport } from './routes/_protected/settings/mailboxes/new'
import { Route as ProtectedSettingsCrmConnectionIdMappingRouteImport } from './routes/_protected/settings/crm/$connectionId/mapping'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComposeRoute = ProtectedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProspectsIndexRoute = ProtectedProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiNangoWebhookRoute = ApiNangoWebhookRouteImport.update({
  id: '/api/nango/webhook',
  path: '/api/nango/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProspectsImportRoute =
  ProtectedProspectsImportRouteImport.update({
    id: '/prospects/import',
    path: '/prospects/import',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProspectsIdRoute = ProtectedProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsMailboxesIndexRoute =
  ProtectedSettingsMailboxesIndexRouteImport.update({
    id: '/settings/mailboxes/',
    path: '/settings/mailboxes/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsCrmIndexRoute =
  ProtectedSettingsCrmIndexRouteImport.update({
    id: '/settings/crm/',
    path: '/settings/crm/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMailboxesNewRoute =
  ProtectedSettingsMailboxesNewRouteImport.update({
    id: '/settings/mailboxes/new',
    path: '/settings/mailboxes/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsCrmConnectionIdMappingRoute =
  ProtectedSettingsCrmConnectionIdMappingRouteImport.update({
    id: '/settings/crm/$connectionId/mapping',
    path: '/settings/crm/$connectionId/mapping',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compose': typeof ProtectedComposeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/prospects/$id': typeof ProtectedProspectsIdRoute
  '/prospects/import': typeof ProtectedProspectsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/prospects/': typeof ProtectedProspectsIndexRoute
  '/settings/mailboxes/new': typeof ProtectedSettingsMailboxesNewRoute
  '/settings/crm/': typeof ProtectedSettingsCrmIndexRoute
  '/settings/mailboxes/': typeof ProtectedSettingsMailboxesIndexRoute
  '/settings/crm/$connectionId/mapping': typeof ProtectedSettingsCrmConnectionIdMappingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compose': typeof ProtectedComposeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/prospects/$id': typeof ProtectedProspectsIdRoute
  '/prospects/import': typeof ProtectedProspectsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/prospects': typeof ProtectedProspectsIndexRoute
  '/settings/mailboxes/new': typeof ProtectedSettingsMailboxesNewRoute
  '/settings/crm': typeof ProtectedSettingsCrmIndexRoute
  '/settings/mailboxes': typeof ProtectedSettingsMailboxesIndexRoute
  '/settings/crm/$connectionId/mapping': typeof ProtectedSettingsCrmConnectionIdMappingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/compose': typeof ProtectedComposeRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/prospects/$id': typeof ProtectedProspectsIdRoute
  '/_protected/prospects/import': typeof ProtectedProspectsImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/_protected/prospects/': typeof ProtectedProspectsIndexRoute
  '/_protected/settings/mailboxes/new': typeof ProtectedSettingsMailboxesNewRoute
  '/_protected/settings/crm/': typeof ProtectedSettingsCrmIndexRoute
  '/_protected/settings/mailboxes/': typeof ProtectedSettingsMailboxesIndexRoute
  '/_protected/settings/crm/$connectionId/mapping': typeof ProtectedSettingsCrmConnectionIdMappingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/compose'
    | '/dashboard'
    | '/prospects/$id'
    | '/prospects/import'
    | '/api/auth/$'
    | '/api/nango/webhook'
    | '/prospects/'
    | '/settings/mailboxes/new'
    | '/settings/crm/'
    | '/settings/mailboxes/'
    | '/settings/crm/$connectionId/mapping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/compose'
    | '/dashboard'
    | '/prospects/$id'
    | '/prospects/import'
    | '/api/auth/$'
    | '/api/nango/webhook'
    | '/prospects'
    | '/settings/mailboxes/new'
    | '/settings/crm'
    | '/settings/mailboxes'
    | '/settings/crm/$connectionId/mapping'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/compose'
    | '/_protected/dashboard'
    | '/_protected/prospects/$id'
    | '/_protected/prospects/import'
    | '/api/auth/$'
    | '/api/nango/webhook'
    | '/_protected/prospects/'
    | '/_protected/settings/mailboxes/new'
    | '/_protected/settings/crm/'
    | '/_protected/settings/mailboxes/'
    | '/_protected/settings/crm/$connectionId/mapping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNangoWebhookRoute: typeof ApiNangoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/compose': {
      id: '/_protected/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ProtectedComposeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/prospects/': {
      id: '/_protected/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProtectedProspectsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/nango/webhook': {
      id: '/api/nango/webhook'
      path: '/api/nango/webhook'
      fullPath: '/api/nango/webhook'
      preLoaderRoute: typeof ApiNangoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/prospects/import': {
      id: '/_protected/prospects/import'
      path: '/prospects/import'
      fullPath: '/prospects/import'
      preLoaderRoute: typeof ProtectedProspectsImportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/prospects/$id': {
      id: '/_protected/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProtectedProspectsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/mailboxes/': {
      id: '/_protected/settings/mailboxes/'
      path: '/settings/mailboxes'
      fullPath: '/settings/mailboxes/'
      preLoaderRoute: typeof ProtectedSettingsMailboxesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/crm/': {
      id: '/_protected/settings/crm/'
      path: '/settings/crm'
      fullPath: '/settings/crm/'
      preLoaderRoute: typeof ProtectedSettingsCrmIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/mailboxes/new': {
      id: '/_protected/settings/mailboxes/new'
      path: '/settings/mailboxes/new'
      fullPath: '/settings/mailboxes/new'
      preLoaderRoute: typeof ProtectedSettingsMailboxesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/crm/$connectionId/mapping': {
      id: '/_protected/settings/crm/$connectionId/mapping'
      path: '/settings/crm/$connectionId/mapping'
      fullPath: '/settings/crm/$connectionId/mapping'
      preLoaderRoute: typeof ProtectedSettingsCrmConnectionIdMappingRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedComposeRoute: typeof ProtectedComposeRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedProspectsIdRoute: typeof ProtectedProspectsIdRoute
  ProtectedProspectsImportRoute: typeof ProtectedProspectsImportRoute
  ProtectedProspectsIndexRoute: typeof ProtectedProspectsIndexRoute
  ProtectedSettingsMailboxesNewRoute: typeof ProtectedSettingsMailboxesNewRoute
  ProtectedSettingsCrmIndexRoute: typeof ProtectedSettingsCrmIndexRoute
  ProtectedSettingsMailboxesIndexRoute: typeof ProtectedSettingsMailboxesIndexRoute
  ProtectedSettingsCrmConnectionIdMappingRoute: typeof ProtectedSettingsCrmConnectionIdMappingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedComposeRoute: ProtectedComposeRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProspectsIdRoute: ProtectedProspectsIdRoute,
  ProtectedProspectsImportRoute: ProtectedProspectsImportRoute,
  ProtectedProspectsIndexRoute: ProtectedProspectsIndexRoute,
  ProtectedSettingsMailboxesNewRoute: ProtectedSettingsMailboxesNewRoute,
  ProtectedSettingsCrmIndexRoute: ProtectedSettingsCrmIndexRoute,
  ProtectedSettingsMailboxesIndexRoute: ProtectedSettingsMailboxesIndexRoute,
  ProtectedSettingsCrmConnectionIdMappingRoute:
    ProtectedSettingsCrmConnectionIdMappingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNangoWebhookRoute: ApiNangoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
